name: tracker


services:
  initiate:
    build: ./backend/
    depends_on: 
      - db
    restart: on-failure
    volumes:
      - ./backend/:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: tracker
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
